// 菜单
const SHOW_MENU = "SHOW_MENU";
const HIDE_MENU = "HIDE_MENU";

// 字体设置栏
const SHOW_FONT_SETTING = "SHOW_FONT_SETTING";
const SET_FONT_SIZE = "SET_FONT_SIZE";

// 变更主题
const SHOW_THEME_SETTING = "SHOW_THEME_SETTING";
const SET_THEME = "SET_THEME";

// 进度条
const SHOW_PROGRESS = "SHOW_PROGRESS";
const IS_LOCATIONS_AVAILABLE = "IS_LOCATIONS_AVAILABLE";
const SET_PROGRESS = "SET_PROGRESS";

// 目录
const GET_CATALOG = "GET_CATALOG";
const NAVIGATE_TO = "NAVIGATE_TO";

export {
  SHOW_MENU,
  HIDE_MENU,
  SHOW_FONT_SETTING,
  SET_FONT_SIZE,
  SHOW_THEME_SETTING,
  SET_THEME,
  SHOW_PROGRESS,
  IS_LOCATIONS_AVAILABLE,
  SET_PROGRESS,
  GET_CATALOG,
  NAVIGATE_TO
};
