// 菜单
const SHOW_MENU = "SHOW_MENU";
const HIDE_MENU = "HIDE_MENU";

// 字体设置栏
const SHOW_FONT_SETTING = "SHOW_FONT_SETTING";
const SET_FONT_SIZE = "SET_FONT_SIZE";

// 变更主题
const SHOW_THEME_SETTING = "SHOW_THEME_SETTING";
const SET_THEME = "SET_THEME";

export {
  SHOW_MENU,
  HIDE_MENU,
  SHOW_FONT_SETTING,
  SET_FONT_SIZE,
  SHOW_THEME_SETTING,
  SET_THEME
};
