// 菜单
const SHOW_MENU = "SHOW_MENU";
const HIDE_MENU = "HIDE_MENU";

// 字体设置栏
const SHOW_FONT_SETTING = "SHOW_FONT_SETTING";
const SET_FONT_SIZE = "SET_FONT_SIZE";

export { SHOW_MENU, HIDE_MENU, SHOW_FONT_SETTING, SET_FONT_SIZE };
